apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: QuantumBallot-backend
spec:
  selector:
    app: QuantumBallot-backend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 3000 # Container port (backend_port)
  type: ClusterIP # Use LoadBalancer or NodePort if external access needed directly (Ingress is preferred)
